Fix type error on stable
Stable is broken when running pnpm without the lockfile:

```
packages/macros/tests/babel/helpers.ts:85:15 - error TS2454: Variable 'mode' is used before being assigned.
```

Applying same fix as on `main`: https://github.com/embroider-build/embroider/pull/2184/commits/31ed2c223e446b744962d96ab58712199551fd37